# Generated by Django 4.1.5 on 2023-02-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Тема')),
                ('context', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'важная новость',
                'verbose_name_plural': 'новости проекта',
            },
        ),
    ]
