# Generated by Django 4.1.5 on 2023-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='context',
            field=models.TextField(max_length=250, verbose_name='Сообщение'),
        ),
    ]
